### PR TITLE
Fix using databasemanager config file to connect the database.

### PR DESCRIPTION
**Pull request by congpeijun**

### CODE REVIEW

**Comment by h-wang** [comment]
@congpeijun we kind of trying not to use database manager

**Comment by congpeijun** [comment]
@h-wang Ok, but the readme.md file shows two way to connect the database. may update the document

**Comment by h-wang** [comment]
@congpeijun i think u r right 👍 this one is using database manager

**Comment by joostfaassen** [comment]
🎉

**Pull request merged**
